# Generated by Django 3.1.2 on 2022-04-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
